// Application/GlobalUsings

global using HotelBookingPlatform.Domain.DTOs.Amenity;
global using HotelBookingPlatform.Domain.DTOs.Booking;
global using HotelBookingPlatform.Domain.Enums;
global using HotelBookingPlatform.Domain.DTOs.Room;
global using HotelBookingPlatform.Domain.DTOs.RoomClass;
global using HotelBookingPlatform.Domain.DTOs.Review;
global using HotelBookingPlatform.Domain.DTOs.Discount;
global using HotelBookingPlatform.Domain.DTOs.HomePage;
global using HotelBookingPlatform.Domain.DTOs.Hotel;
global using Microsoft.AspNetCore.Mvc;
global using HotelBookingPlatform.Domain.DTOs.InvoiceRecord;
global using Microsoft.AspNetCore.Http;
global using HotelBookingPlatform.Domain.DTOs.Owner;
global using AutoMapper;
global using HotelBookingPlatform.Domain.Entities;
global using HotelBookingPlatform.Domain;
global using HotelBookingPlatform.Application.Core.Abstracts;
global using HotelBookingPlatform.Domain.Exceptions;
global using KeyNotFoundException = HotelBookingPlatform.Domain.Exceptions.KeyNotFoundException;
global using HotelBookingPlatform.Domain.DTOs.City;
global using System.Linq.Expressions;
global using InvalidOperationException = HotelBookingPlatform.Domain.Exceptions.InvalidOperationException;
global using Microsoft.Extensions.Configuration;
global using Microsoft.EntityFrameworkCore;
global using HotelBookingPlatform.Domain.Helpers;
global using HotelBookingPlatform.Domain.IServices;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Options;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text;
global using UnauthorizedAccessException = HotelBookingPlatform.Domain.Exceptions.UnauthorizedAccessException;
global using FluentValidation;
global using FluentValidation.AspNetCore;
global using HotelBookingPlatform.Application.Core.Implementations;
global using HotelBookingPlatform.Application.Validator;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using HotelBookingPlatform.Domain.ILogger;
global using CloudinaryDotNet.Actions;
global using CloudinaryDotNet;

